// Mocks generated by Mockito 5.4.4 from annotations
// in sartor_order_management/test/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sartor_order_management/models/order_model.dart' as _i2;
import 'package:sartor_order_management/models/service.dart' as _i5;
import 'package:sartor_order_management/models/service_category.dart' as _i6;
import 'package:sartor_order_management/services/order_repository.dart' as _i7;
import 'package:sartor_order_management/services/service_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceRepository extends _i1.Mock implements _i3.ServiceRepository {
  MockServiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.Service>> getServices() => (super.noSuchMethod(
        Invocation.method(
          #getServices,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Service>>.empty(),
      ) as _i4.Stream<List<_i5.Service>>);

  @override
  _i4.Future<List<_i6.ServiceCategory>> getServiceCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i6.ServiceCategory>>.value(
            <_i6.ServiceCategory>[]),
      ) as _i4.Future<List<_i6.ServiceCategory>>);

  @override
  _i4.Future<void> addService(_i5.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #addService,
          [service],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateService(_i5.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [service],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteService(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteService,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i7.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Order>> getOrders(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.Order>>.value(<_i2.Order>[]),
      ) as _i4.Future<List<_i2.Order>>);

  @override
  _i4.Future<List<_i2.OrderSummary>> fetchMyOrders() => (super.noSuchMethod(
        Invocation.method(
          #fetchMyOrders,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.OrderSummary>>.value(<_i2.OrderSummary>[]),
      ) as _i4.Future<List<_i2.OrderSummary>>);

  @override
  _i4.Future<void> cancelOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [orderId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Order>> getUserOrders(
    String? userId, {
    String? query,
    List<String>? statuses,
    DateTime? startDate,
    DateTime? endDate,
    String? serviceType,
    int? page = 1,
    int? pageSize = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserOrders,
          [userId],
          {
            #query: query,
            #statuses: statuses,
            #startDate: startDate,
            #endDate: endDate,
            #serviceType: serviceType,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i2.Order>>.value(<_i2.Order>[]),
      ) as _i4.Future<List<_i2.Order>>);

  @override
  _i4.Future<_i2.Order> createOrder({
    required String? userId,
    required String? measurementId,
    required int? totalCents,
    required String? notes,
    required List<Map<String, dynamic>>? items,
    String? status = r'pending',
    String? trackingId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #userId: userId,
            #measurementId: measurementId,
            #totalCents: totalCents,
            #notes: notes,
            #items: items,
            #status: status,
            #trackingId: trackingId,
          },
        ),
        returnValue: _i4.Future<_i2.Order>.value(_FakeOrder_0(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #userId: userId,
              #measurementId: measurementId,
              #totalCents: totalCents,
              #notes: notes,
              #items: items,
              #status: status,
              #trackingId: trackingId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Order>);
}
