final List<Map<String, dynamic>> defaultServices = [
  {
    'id': 1,
    'name': 'Two-Piece Suit',
    'description': 'A classic two-piece suit for all occasions.',
    'price_cents': 25000,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 15,
  },
  {
    'id': 2,
    'name': 'Three-Piece Suit',
    'description': 'An elegant three-piece suit for a formal look.',
    'price_cents': 35000,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 20,
  },
  {
    'id': 3,
    'name': 'Dress Shirt',
    'description': 'A crisp, tailored dress shirt.',
    'price_cents': 7500,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 10,
  },
  {
    'id': 4,
    'name': 'Trousers',
    'description': 'Custom-fit trousers for any style.',
    'price_cents': 12000,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 10,
  },
  {
    'id': 5,
    'name': 'Blazer',
    'description': 'A stylish blazer to complete your look.',
    'price_cents': 18000,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 15,
  },
  {
    'id': 6,
    'name': 'Waistcoat',
    'description': 'A sharp waistcoat to wear with or without a suit.',
    'price_cents': 9000,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 12,
  },
  {
    'id': 7,
    'name': 'Overcoat',
    'description': 'A warm and stylish overcoat for the colder months.',
    'price_cents': 30000,
    'category_id': 1,
    'is_active': true,
    'delivery_days': 25,
  },
  {
    'id': 8,
    'name': 'Tie',
    'description': 'A silk tie to complement your suit.',
    'price_cents': 4000,
    'category_id': 5,
    'is_active': true,
    'delivery_days': 5,
  },
];
