// Mocks generated by Mockito 5.4.4 from annotations
// in sartor_order_management/test/features/orders/new_order_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sartor_order_management/models/service.dart' as _i4;
import 'package:sartor_order_management/models/service_category.dart' as _i5;
import 'package:sartor_order_management/services/service_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ServiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceRepository extends _i1.Mock implements _i2.ServiceRepository {
  MockServiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Service>> getServices() => (super.noSuchMethod(
        Invocation.method(
          #getServices,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Service>>.value(<_i4.Service>[]),
      ) as _i3.Future<List<_i4.Service>>);

  @override
  _i3.Future<List<_i5.ServiceCategory>> getServiceCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i5.ServiceCategory>>.value(
            <_i5.ServiceCategory>[]),
      ) as _i3.Future<List<_i5.ServiceCategory>>);

  @override
  _i3.Future<void> addService(_i4.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #addService,
          [service],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateService(_i4.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [service],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteService(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteService,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
